const FETCH_JOBS = 'FETCH_JOBS';
const UPDATE_SELECTED_FILTERS = 'UPDATE_SELECTED_FILTERS';
const UPDATE_INITIAL_JOBS = 'UPDATE_INITIAL_JOBS';

export { FETCH_JOBS, UPDATE_SELECTED_FILTERS, UPDATE_INITIAL_JOBS };
