const FETCH_JOBS = 'FETCH_JOBS';
const UPDATE_SELECTED_FILTERS = 'UPDATE_SELECTED_FILTERS';
const UPDATE_ON_SECOND_FILTER = 'UPDATE_ON_SECOND_FILTER';

export { FETCH_JOBS, UPDATE_SELECTED_FILTERS, UPDATE_ON_SECOND_FILTER };
